/*
 ***********************************************************************
 * Version      Date            Name            Description
 * =====================================================================
 * V1.0         07-08-2022      C. Domicewicz   Add Method implemented
 * *********************************************************************
*/
public with sharing class Calculator {
    public Calculator() {

    }    

    public integer add(integer a, integer b) {
        return a + b;
    }

}
